### PR TITLE
fix: add missing method types for moduleContainer

### LINKED ISSUE #119: Module testing page is missing the "addModule" option
in [module testing docs](https://test-utils.nuxtjs.org/api-reference/module-testing) page It only shows the following options:
- `addPlugin`
- `addLayout` 
- `addErrorLayout`
- `addServerMiddleware` 
- `requireModule`

But the `addModule` option  is not documented although it can be used!

### PR DESCRIPTION
**Pull request by achimoraites**
Included the `addModule` option in the [module testing page](https://test-utils.nuxtjs.org/api-reference/module-testing)

fixes #119

### CODE REVIEW

**Comment by mrazauskas** [comment]
Would be good to fix [typings](https://github.com/nuxt/test-utils/blob/e3ad52ef091a8b7a541b2add0fda4894626e7eb8/src/assertions.ts#L5) as well.

**Comment by achimoraites** [comment]
Thanks a lot @mrazauskas !
I will fix them as well :)

**Review by ricardogobbosouza — APPROVED** [review]

**Comment by pi0** [comment]
Also missing: `addTemplate`, `extendBuild`, `extendBuild`, `addModule` (reference: https://github.com/nuxt/nuxt.js/blob/dev/packages/core/src/module.js)

**Comment by achimoraites** [comment]
Thanks @pi0 !
Will include them as well!

**Review by pi0 — APPROVED** [review]

**Pull request merged**
