### PR TITLE
test: add `jest` example/test

### PR DESCRIPTION
**Pull request by danielroe**
resolves https://github.com/nuxt/test-utils/issues/218

### CODE REVIEW

**Comment by barelyhuman** [comment]
Screenshot 2023-11-06 at 11 55 33 PM


Was this an issue that was already solved?

**Comment by danielroe** [comment]
You may need to build first with `pnpm prepack`.

**Comment by barelyhuman** [comment]
Screenshot 2023-11-07 at 12 24 36 AM


Works with a `.cjs` file of jest, will see if I can get it working with `.ts` config as well

**Comment by barelyhuman** [comment]
Opened: https://github.com/nuxt/test-utils/pull/225/

**Comment by danielroe** [comment]
I think there's already an eslint config 🤔

**Comment by barelyhuman** [comment]
> I think there's already an eslint config 🤔

top level, yes. 

It's not inheriting it all the way in, ends up using my defaults

**Comment by barelyhuman** [comment]
> Ah, I think that's okay. We want the examples to be separately cloneable, and we run the autofix from the top.

Oh okay 👌

**Comment by userquin** [comment]
imagen

**Comment by barelyhuman** [comment]
Yeah, I ended up adding an import for it manually. 

jest and its sandbox doesn't like a lot of things

**Comment by userquin** [comment]
> Yeah, I ended up adding an import for it manually.
> 
> jest and its sandbox doesn't like a lot of things

https://github.com/nuxt/test-utils/pull/224#issuecomment-1796140588

**Comment by userquin** [comment]
Now Windows fs error:

imagen

**Comment by barelyhuman** [comment]
That's from my commits? I didn't test on windows but let me know if you have a hard time

**Comment by userquin** [comment]
> That's from my commits? I didn't test on windows but let me know if you have a hard time

No, just testing on my local, but both seem almost identical, I'll check with your changes.

**Comment by userquin** [comment]
can you test in your local adding `.npmrc` (root folder) with `shell-emulator=true` and changing the script to `"test": "NODE_OPTIONS=--experimental-vm-modules jest"`?

The error on my local Windows laptop:
```shell
test/server.e2e.spec.ts 
  ● setup

    TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:\\\D:\work\issues-repos\test-utils-pr-
224\node_modules\.pnpm\nuxt@3.8.1_@types+node@20.8.10_eslint@8.53.0_rollup@3.29.4_typescript@5.2.2_vite@4.5.0\node_modules\nuxt\dist'

      91 |     });
      92 |   }
    > 93 |   ctx.nuxt = await kit.loadNuxt({
         |              ^
      94 |     cwd: ctx.options.rootDir,
      95 |     dev: ctx.options.dev,
      96 |     overrides: ctx.options.nuxtConfig,

      at Function.createRequire (../../node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1618:23)
      at module.exports (../../node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:639)
      at createJITI (../../node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:250383)
      at Object.<anonymous>.module.exports (../../node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/lib/index.js:14:10)
      at setup (../../node_modules/.pnpm/nuxt@3.8.1_@types+node@20.8.10_eslint@8.53.0_rollup@3.29.4_typescript@5.2.2_vite@4.5.0/node_modules/nuxt/dist/index.mjs:3052:28)
      at normalizedModule (../../node_modules/.pnpm/@nuxt+kit@3.8.1_rollup@3.29.4/node_modules/@nuxt/kit/dist/index.mjs:2141:37)
      at installModule (../../node_modules/.pnpm/@nuxt+kit@3.8.1_rollup@3.29.4/node_modules/@nuxt/kit/dist/index.mjs:2439:95)
      at initNuxt (../../node_modules/.pnpm/nuxt@3.8.1_@types+node@20.8.10_eslint@8.53.0_rollup@3.29.4_typescript@5.2.2_vite@4.5.0/node_modules/nuxt/dist/index.mjs:3696:7)
      at loadNuxt (../../node_modules/.pnpm/nuxt@3.8.1_@types+node@20.8.10_eslint@8.53.0_rollup@3.29.4_typescript@5.2.2_vite@4.5.0/node_modules/nuxt/dist/index.mjs:3783:5)
      at Module.loadNuxt (../../node_modules/.pnpm/@nuxt+kit@3.8.1_rollup@3.29.4/node_modules/@nuxt/kit/dist/index.mjs:2584:19)
      at loadFixture (../../dist/index.mjs:93:14)
      at Object.setup2 (../../dist/index.mjs:154:7)
```

**Comment by userquin** [comment]
same error with latest changes here reverting `"@nuxt/test-utils": "workspace:*"` to use `"@nuxt/test-utils": "latest"` on my local

**Pull request merged**
